### ISSUE TITLE
specUrl => local file

### ISSUE THREAD

**Issue by gfelot** [APIs-guru/create-react-app-redoc#1]
When I try to add my `.yaml` file I get an error 
```
"http://localhost:3000/openapi.yaml" is not a valid JSON Schema
```
If I put it to the root or public/
How can reference specUrl to a local file ?

**Comment by RomanHotsiy** [comment]
Could you set up a demo repo so I can easily reproduce it?
Thx

**Comment by gfelot** [comment]
Sure : git@github.com:gfelot/redoc_cra_test.git

**Comment by RomanHotsiy** [comment]
Looks like you're using the wrong URL. You should not depend on relative location for `/public` folder.
It is explicitly specified in CRA readme:

![image](https://user-images.githubusercontent.com/3975738/44132691-e304ec60-a063-11e8-87ef-9c80347bbea3.png)
