### ISSUE TITLE
Failed to compile ./node_modules/redoc/bundles/redoc.lib.js Module not found: Can't resolve 'core-js/es/promise' in 

### ISSUE THREAD

**Issue by Angelk90** [APIs-guru/create-react-app-redoc#15]
Hi @RomanHotsiy , 

I'm having the following problem:
`
Failed to compile ./node_modules/redoc/bundles/redoc.lib.js Module not found: Can't resolve 'core-js / es / promise' in
`

I cloned the project, I installed the modules from npm, I changed the original project's url because it pointed to a page with the following:
`https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml`

But it does not work.

**Comment by RomanHotsiy** [comment]
Fixed by #16
