### ISSUE TITLE
core-js Module not found: Can't resolve 'core-js/es/promise' in

### ISSUE THREAD

**Issue by cc7gs** [APIs-guru/create-react-app-redoc#17]
Hi @RomanHotsiy ,
I'm having the following problem:
![image](https://user-images.githubusercontent.com/36002392/93869799-e1e51180-fcfe-11ea-901d-7713b49b4c33.png)

#16 ,Doesn't work for me

**Comment by ohansemmanuel** [comment]
Quick dirty fix to get you going. Install deps within the redoc module 

```sh
cd node_modules/redoc && npm install
```
